/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package de.westlb.mgb.client.mail.parser;

public interface ParserConstants {

  int EOF = 0;
  int ENDIF = 1;
  int LBRACKET = 2;
  int RBRACKET = 3;
  int LETTER = 4;
  int NUMBER = 5;
  int VAR = 6;
  int IF = 7;
  int TEXT = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"[endif]\"",
    "\"[\"",
    "\"]\"",
    "<LETTER>",
    "<NUMBER>",
    "<VAR>",
    "<IF>",
    "<TEXT>",
  };

}
